import type { AppNoteItem } from '@kriyan/client-core'
import { Ionicons } from '@expo/vector-icons'
import { useState } from 'react'
import { Alert, Pressable, Text, View } from 'react-native'

import { Card, ConnectionBanner, Field, PrimaryButton, Screen, SectionHeader, uiStyles } from '@/components/product-ui'
import { Colors } from '@/constants/theme'
import { useColorScheme } from '@/hooks/use-color-scheme'
import { createClientId, tipTapDocumentFromText, wordCount } from '@/lib/ids'
import { useProductStore } from '@/lib/product-store'
import { inspectTipTapForPlainTextEditing } from '@/lib/tiptap-preservation'

export default function NotesScreen() {
  const { notes, runWrite } = useProductStore(); const colors = Colors[useColorScheme() ?? 'light']; const [editing, setEditing] = useState<AppNoteItem | 'new' | null>(null); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [tags, setTags] = useState(''); const [entityId, setEntityId] = useState(''); const [contentReadOnlyReason, setContentReadOnlyReason] = useState<string>()
  const begin = (note?: AppNoteItem) => { const inspection = note ? inspectTipTapForPlainTextEditing(note.contentJson, note.plainTextPreview) : { editable: true as const, text: '' }; setEditing(note ?? 'new'); setTitle(note?.title ?? ''); setBody(inspection.text); setContentReadOnlyReason(inspection.editable ? undefined : inspection.reason); setTags(note?.tags.join(', ') ?? ''); setEntityId(note?.entityId ?? '') }
  const save = async () => { if (!contentReadOnlyReason && !body.trim()) return Alert.alert('Note is empty', 'Write something before saving.'); const values = tags.split(',').map((tag) => tag.trim().toLowerCase()).filter(Boolean); const metadata = { title: title.trim() || null, tags: values, entityId: entityId.trim() || null }; const content = { contentJson: tipTapDocumentFromText(body), plainTextPreview: body.trim(), wordCount: wordCount(body) }; const patch = contentReadOnlyReason ? metadata : { ...metadata, ...content }; const result = editing === 'new' ? await runWrite((repo) => { const id = createClientId('note'); return repo.notesV1.create({ noteId: id, idempotencyKey: `mobile:${id}`, title: title.trim() || undefined, contentJson: content.contentJson, plainTextPreview: content.plainTextPreview, wordCount: content.wordCount, tags: values, entityId: entityId.trim() || undefined }) }) : editing ? await runWrite((repo) => repo.notesV1.update({ noteId: editing.noteId, expectedRevision: editing.revision, patch })) : null; if (result?.ok) setEditing(null) }
  return <Screen><ConnectionBanner /><SectionHeader title="Notes" action={editing ? 'Cancel' : 'Add'} onAction={editing ? () => setEditing(null) : () => begin()} />{editing ? <Card><Field label="Title" accessibilityLabel="Note title" value={title} onChangeText={setTitle} placeholder="Untitled note" />{contentReadOnlyReason ? <Text accessibilityRole="alert" selectable style={{ color: colors.warning, fontSize: 13 }}>{contentReadOnlyReason} You can still update metadata without changing the original content.</Text> : null}<Field label="Content" accessibilityLabel="Note content" value={body} onChangeText={setBody} editable={!contentReadOnlyReason} multiline placeholder="Capture the thought…" /><Field label="Tags" value={tags} onChangeText={setTags} placeholder="idea, project" /><Field label="Entity ID" value={entityId} onChangeText={setEntityId} placeholder="entity:…" /><Text selectable style={{ color: colors.textSecondary, fontSize: 13 }}>{wordCount(body)} words · {contentReadOnlyReason ? 'rich content preserved byte-for-byte' : 'stored as TipTap-compatible JSON with a shared-contract preview'}</Text><PrimaryButton label={contentReadOnlyReason ? 'Save metadata' : 'Save note'} icon="checkmark" onPress={() => void save()} /></Card> : null}{notes.map((note) => <Card key={note.noteId}><View style={uiStyles.row}><Ionicons name="document-text-outline" size={24} color={colors.primary} /><View style={uiStyles.grow}><Text selectable style={[uiStyles.title, { color: colors.text }]}>{note.title || 'Untitled note'}</Text><Text selectable numberOfLines={3} style={{ color: colors.textSecondary, lineHeight: 20 }}>{note.plainTextPreview}</Text><Text selectable style={[uiStyles.meta, { color: colors.textMuted }]}>{note.wordCount} words · revision {note.revision}</Text></View><Pressable accessibilityLabel={`Edit ${note.title || 'note'}`} style={uiStyles.iconButton} onPress={() => begin(note)}><Ionicons name="pencil" size={20} color={colors.primary} /></Pressable><Pressable accessibilityLabel={`Delete ${note.title || 'note'}`} style={uiStyles.iconButton} onPress={() => void runWrite((repo) => repo.notesV1.tombstone(note.noteId, note.revision))}><Ionicons name="trash-outline" size={20} color={colors.error} /></Pressable></View></Card>)}</Screen>
}
