import type { AppNoteItem } from '@kriyan/client-core'
import { Ionicons } from '@expo/vector-icons'
import { useState } from 'react'
import { Alert, Pressable, Text, View } from 'react-native'

import { Card, ConnectionBanner, Field, PrimaryButton, Screen, SectionHeader, uiStyles } from '@/components/product-ui'
import { Colors } from '@/constants/theme'
import { useColorScheme } from '@/hooks/use-color-scheme'
import { createClientId, tipTapDocumentFromText, wordCount } from '@/lib/ids'
import { useProductStore } from '@/lib/product-store'

export default function NotesScreen() {
  const { notes, runWrite } = useProductStore(); const colors = Colors[useColorScheme() ?? 'light']; const [editing, setEditing] = useState<AppNoteItem | 'new' | null>(null); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [tags, setTags] = useState(''); const [entityId, setEntityId] = useState('')
  const begin = (note?: AppNoteItem) => { setEditing(note ?? 'new'); setTitle(note?.title ?? ''); setBody(note?.plainTextPreview ?? ''); setTags(note?.tags.join(', ') ?? ''); setEntityId(note?.entityId ?? '') }
  const save = async () => { if (!body.trim()) return Alert.alert('Note is empty', 'Write something before saving.'); const values = tags.split(',').map((tag) => tag.trim().toLowerCase()).filter(Boolean); const patch = { title: title.trim() || null, contentJson: tipTapDocumentFromText(body), plainTextPreview: body.trim(), wordCount: wordCount(body), tags: values, entityId: entityId.trim() || null }; const result = editing === 'new' ? await runWrite((repo) => { const id = createClientId('note'); return repo.notesV1.create({ noteId: id, idempotencyKey: `mobile:${id}`, title: title.trim() || undefined, contentJson: patch.contentJson, plainTextPreview: patch.plainTextPreview, wordCount: patch.wordCount, tags: values, entityId: entityId.trim() || undefined }) }) : editing ? await runWrite((repo) => repo.notesV1.update({ noteId: editing.noteId, expectedRevision: editing.revision, patch })) : null; if (result?.ok) setEditing(null) }
  return <Screen><ConnectionBanner /><SectionHeader title="Notes" action={editing ? 'Cancel' : 'Add'} onAction={editing ? () => setEditing(null) : () => begin()} />{editing ? <Card><Field label="Title" accessibilityLabel="Note title" value={title} onChangeText={setTitle} placeholder="Untitled note" /><Field label="Content" accessibilityLabel="Note content" value={body} onChangeText={setBody} multiline placeholder="Capture the thought…" /><Field label="Tags" value={tags} onChangeText={setTags} placeholder="idea, project" /><Field label="Entity ID" value={entityId} onChangeText={setEntityId} placeholder="entity:…" /><Text selectable style={{ color: colors.textSecondary, fontSize: 13 }}>{wordCount(body)} words · stored as TipTap-compatible JSON with a shared-contract preview</Text><PrimaryButton label="Save note" icon="checkmark" onPress={() => void save()} /></Card> : null}{notes.map((note) => <Card key={note.noteId}><View style={uiStyles.row}><Ionicons name="document-text-outline" size={24} color={colors.primary} /><View style={uiStyles.grow}><Text selectable style={[uiStyles.title, { color: colors.text }]}>{note.title || 'Untitled note'}</Text><Text selectable numberOfLines={3} style={{ color: colors.textSecondary, lineHeight: 20 }}>{note.plainTextPreview}</Text><Text selectable style={[uiStyles.meta, { color: colors.textMuted }]}>{note.wordCount} words · revision {note.revision}</Text></View><Pressable accessibilityLabel={`Edit ${note.title || 'note'}`} style={uiStyles.iconButton} onPress={() => begin(note)}><Ionicons name="pencil" size={20} color={colors.primary} /></Pressable><Pressable accessibilityLabel={`Delete ${note.title || 'note'}`} style={uiStyles.iconButton} onPress={() => void runWrite((repo) => repo.notesV1.tombstone(note.noteId, note.revision))}><Ionicons name="trash-outline" size={20} color={colors.error} /></Pressable></View></Card>)}</Screen>
}
