import type { ReminderDeliveryPolicy, ReminderItem } from '@kriyan/client-core'
import { Ionicons } from '@expo/vector-icons'
import { useState } from 'react'
import { Alert, Pressable, Text, View } from 'react-native'

import { Card, ConnectionBanner, Field, PrimaryButton, Screen, SectionHeader, uiStyles } from '@/components/product-ui'
import { Colors } from '@/constants/theme'
import { useColorScheme } from '@/hooks/use-color-scheme'
import { createClientId, notificationIntentKey } from '@/lib/ids'
import { cancelReminderNotifications, scheduleReminderNotification } from '@/lib/notifications'
import { useProductStore } from '@/lib/product-store'

export default function RemindersScreen() {
  const { reminders, runWrite, repository, refresh } = useProductStore(); const colors = Colors[useColorScheme() ?? 'light']
  const [editing, setEditing] = useState<ReminderItem | 'new' | null>(null); const [message, setMessage] = useState(''); const [when, setWhen] = useState(''); const [policy, setPolicy] = useState<ReminderDeliveryPolicy>('normal'); const [linkedTaskId, setLinkedTaskId] = useState(''); const [entityId, setEntityId] = useState('')
  const begin = (reminder?: ReminderItem) => { setEditing(reminder ?? 'new'); setMessage(reminder?.message ?? ''); setWhen(reminder ? new Date(reminder.nextFireAt ?? reminder.remindAt).toISOString().slice(0, 16) : ''); setPolicy(reminder?.deliveryPolicy ?? 'normal'); setLinkedTaskId(reminder?.linkedTaskId ?? ''); setEntityId(reminder?.entityId ?? '') }
  const schedule = async (reminder: ReminderItem) => { const scheduledFor = reminder.nextFireAt ?? reminder.remindAt; const result = await scheduleReminderNotification({ reminderId: reminder.reminderId, message: reminder.message, scheduledFor, deliveryPolicy: reminder.deliveryPolicy ?? 'normal' }); if (!result.ok) Alert.alert('Reminder saved', `${result.message} You can enable notifications later in system settings.`); if (repository) { const intentId = createClientId('notification'); await repository.notificationIntentsV1.create({ notificationIntentId: intentId, idempotencyKey: result.ok ? result.intentKey : notificationIntentKey(reminder.reminderId, scheduledFor), reminderId: reminder.reminderId, scheduledFor, deliveryPolicy: reminder.deliveryPolicy ?? 'normal', dedupeKey: notificationIntentKey(reminder.reminderId, scheduledFor), targetDeviceId: 'mobile:local' }); await refresh() } }
  const save = async () => { const remindAt = new Date(when).getTime(); if (!message.trim() || !Number.isFinite(remindAt)) return Alert.alert('Check reminder', 'Add a message and time like 2026-07-13 17:00.'); const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone; const result = editing === 'new' ? await runWrite((repo) => { const id = createClientId('reminder'); return repo.remindersV1.create({ reminderId: id, idempotencyKey: `mobile:${id}`, message: message.trim(), remindAt, nextFireAt: remindAt, timezone, deliveryPolicy: policy, scheduleKey: `mobile:${id}`, linkedTaskId: linkedTaskId.trim() || undefined, entityId: entityId.trim() || undefined }) }) : editing ? await runWrite((repo) => repo.remindersV1.update({ reminderId: editing.reminderId, expectedRevision: editing.revision, patch: { message: message.trim(), remindAt, nextFireAt: remindAt, timezone, deliveryPolicy: policy, linkedTaskId: linkedTaskId.trim() || null, entityId: entityId.trim() || null } })) : null; if (result?.ok) { await cancelReminderNotifications(result.value.reminderId); await schedule(result.value); setEditing(null) } }
  const acknowledge = async (reminder: ReminderItem) => { await cancelReminderNotifications(reminder.reminderId); await runWrite((repo) => repo.remindersV1.acknowledge(reminder.reminderId, reminder.revision)) }
  const snooze = async (reminder: ReminderItem) => { const next = Date.now() + 10 * 60_000; await cancelReminderNotifications(reminder.reminderId); const result = await runWrite((repo) => repo.remindersV1.snooze(reminder.reminderId, reminder.revision, next)); if (result.ok) await schedule(result.value) }
  return <Screen><ConnectionBanner /><SectionHeader title="Reminders" action={editing ? 'Cancel' : 'Add'} onAction={editing ? () => setEditing(null) : () => begin()} />{editing ? <Card><Field label="Message" accessibilityLabel="Reminder message" value={message} onChangeText={setMessage} placeholder="What should surface?" /><Field label="When" value={when} onChangeText={setWhen} placeholder="2026-07-13 17:00" /><View style={uiStyles.actions}>{(['normal', 'persistent', 'critical'] as const).map((value) => <Pressable accessibilityRole="button" key={value} onPress={() => setPolicy(value)} style={[uiStyles.chip, { backgroundColor: policy === value ? colors.primary : colors.background }]}><Text style={{ color: policy === value ? '#fff' : colors.text }}>{value}</Text></Pressable>)}</View><Text selectable style={{ color: colors.textSecondary, fontSize: 13 }}>Persistent and critical raise Android channel importance only. They do not guarantee delivery, a foreground service, or a full-screen alarm.</Text><Field label="Linked task ID" value={linkedTaskId} onChangeText={setLinkedTaskId} placeholder="task:…" /><Field label="Entity ID" value={entityId} onChangeText={setEntityId} placeholder="entity:…" /><PrimaryButton label="Save reminder" icon="notifications" onPress={() => void save()} /></Card> : null}{reminders.map((reminder) => <Card key={reminder.reminderId}><View style={uiStyles.row}><Ionicons name={reminder.status === 'acknowledged' ? 'notifications-off-outline' : 'notifications-outline'} size={24} color={colors.warning} /><View style={uiStyles.grow}><Text selectable style={[uiStyles.title, { color: colors.text }]}>{reminder.message}</Text><Text selectable style={[uiStyles.meta, { color: colors.textSecondary }]}>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(reminder.nextFireAt ?? reminder.remindAt)} · {reminder.deliveryPolicy}</Text></View><Pressable accessibilityLabel={`Edit ${reminder.message}`} style={uiStyles.iconButton} onPress={() => begin(reminder)}><Ionicons name="pencil" size={20} color={colors.primary} /></Pressable></View><View style={uiStyles.actions}><Pressable accessibilityRole="button" style={[uiStyles.chip, { backgroundColor: colors.background }]} onPress={() => void acknowledge(reminder)}><Text style={{ color: colors.text }}>Acknowledge</Text></Pressable><Pressable accessibilityRole="button" style={[uiStyles.chip, { backgroundColor: colors.background }]} onPress={() => void snooze(reminder)}><Text style={{ color: colors.text }}>Snooze 10m</Text></Pressable><Pressable accessibilityRole="button" style={[uiStyles.chip, { backgroundColor: colors.background }]} onPress={() => { void cancelReminderNotifications(reminder.reminderId); void runWrite((repo) => repo.remindersV1.tombstone(reminder.reminderId, reminder.revision)) }}><Text style={{ color: colors.error }}>Delete</Text></Pressable></View></Card>)}</Screen>
}
