import type { CalendarEventItem } from '@kriyan/client-core'
import { Ionicons } from '@expo/vector-icons'
import { useState } from 'react'
import { Alert, Pressable, Text, View } from 'react-native'

import { Card, ConnectionBanner, Field, PrimaryButton, Screen, SectionHeader, uiStyles } from '@/components/product-ui'
import { Colors } from '@/constants/theme'
import { useColorScheme } from '@/hooks/use-color-scheme'
import { createClientId } from '@/lib/ids'
import { useProductStore } from '@/lib/product-store'

export default function CalendarScreen() {
  const { events, runWrite } = useProductStore(); const colors = Colors[useColorScheme() ?? 'light']
  const [editing, setEditing] = useState<CalendarEventItem | 'new' | null>(null); const [title, setTitle] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [description, setDescription] = useState('')
  const begin = (event?: CalendarEventItem) => { setEditing(event ?? 'new'); setTitle(event?.title ?? ''); setDescription(event?.description ?? ''); setStart(event ? new Date(event.startAt).toISOString().slice(0, 16) : ''); setEnd(event ? new Date(event.endAt).toISOString().slice(0, 16) : '') }
  const save = async () => { const startAt = new Date(start).getTime(); const endAt = new Date(end).getTime(); if (!title.trim() || !Number.isFinite(startAt) || !Number.isFinite(endAt) || endAt <= startAt) return Alert.alert('Check event', 'Add a title and a valid start/end range.'); const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone; const result = editing === 'new' ? await runWrite((repo) => { const id = createClientId('event'); return repo.calendarV1.create({ calendarEventId: id, idempotencyKey: `mobile:${id}`, title: title.trim(), description: description.trim() || undefined, startAt, endAt, timezone, allDay: false }) }) : editing ? await runWrite((repo) => repo.calendarV1.update({ calendarEventId: editing.calendarEventId, expectedRevision: editing.revision, patch: { title: title.trim(), description: description.trim() || null, startAt, endAt } })) : null; if (result?.ok) setEditing(null) }
  return <Screen><ConnectionBanner /><SectionHeader title="Schedule" action={editing ? 'Cancel' : 'Add'} onAction={editing ? () => setEditing(null) : () => begin()} />{editing ? <Card><Field label="Title" accessibilityLabel="Event title" value={title} onChangeText={setTitle} placeholder="Focus block" /><Field label="Description" value={description} onChangeText={setDescription} placeholder="Optional context" /><Field label="Starts" value={start} onChangeText={setStart} placeholder="2026-07-13 14:00" /><Field label="Ends" value={end} onChangeText={setEnd} placeholder="2026-07-13 15:00" /><PrimaryButton label="Save event" icon="checkmark" onPress={() => void save()} /></Card> : null}{events.map((event) => <Card key={event.calendarEventId}><View style={uiStyles.row}><View style={[uiStyles.iconButton, { backgroundColor: colors.background }]}><Ionicons name="calendar-outline" size={22} color={colors.primary} /></View><View style={uiStyles.grow}><Text selectable style={[uiStyles.title, { color: colors.text }]}>{event.title}</Text><Text selectable style={[uiStyles.meta, { color: colors.textSecondary }]}>{new Intl.DateTimeFormat(undefined, { weekday: 'short', hour: 'numeric', minute: '2-digit' }).format(event.startAt)} – {new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(event.endAt)}</Text></View><Pressable accessibilityLabel={`Edit ${event.title}`} style={uiStyles.iconButton} onPress={() => begin(event)}><Ionicons name="pencil" size={20} color={colors.primary} /></Pressable><Pressable accessibilityLabel={`Delete ${event.title}`} style={uiStyles.iconButton} onPress={() => void runWrite((repo) => repo.calendarV1.tombstone(event.calendarEventId, event.revision))}><Ionicons name="trash-outline" size={20} color={colors.error} /></Pressable></View></Card>)}</Screen>
}
